
   
# This is a basic workflow to help you get started with Actions

name: docs-macos

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:  ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby dependencies
      run: |        
        sudo gem install asciidoctor
        sudo gem install asciidoctor-diagram
        sudo gem install ascii_binder
        which asciibinder
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install pyyaml
        pip3 install aura.tar.gz
    - name: build
      run: |        
        python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.10 --no-upstream-fetch
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git init
        git add . 
        git commit -m initial_commit
        asciibinder build
    
    
